### ISSUE TITLE
Improve the jumpscale blockchain code and documentation

### ISSUE THREAD

**Issue by robvanmieghem** [rivine/home#6]
- [x] By default reuse an input address for the change in the Rivine wallet send_money method https://github.com/threefoldtech/jumpscale_lib/issues/98
- [x] Add rivine Create and Open wallet convenience methods https://github.com/threefoldtech/jumpscale_lib/issues/90
- [x] Make the seed optional in the rivine wallet creation https://github.com/threefoldtech/jumpscale_lib/issues/89
- [x] Use the base token value instead of hastings for the txfee in the j.clients.blockchain.rivine.wallet creation https://github.com/threefoldtech/jumpscale_lib/issues/85
- [x] Move j.clients.blockchain.Electrum to j. clients.blockchain.btc.Electrum https://github.com/threefoldtech/jumpscale_lib/issues/82
-  [x] Use the atomic swap transactionid instead of the outputid in j.clients.blockchain.rivine.atomicswap  https://github.com/threefoldtech/jumpscale_lib/issues/81
- [x] Add the Ability to use multiple explorers/daemons to j.clients.blockchain.rivine  https://github.com/threefoldtech/jumpscale_lib/issues/80
- [x] Add a tft client to j.clients.blockchain  https://github.com/threefoldtech/jumpscale_lib/issues/79
- [x] Better documentation for  j.clients.blockchain.rivine https://github.com/threefoldtech/jumpscale_lib/issues/78
- [x] Add an atomic swap walkthrough example for the rivine blockchain client https://github.com/threefoldtech/jumpscale_lib/issues/76 
- [x] Add btc electrum atomic swap support https://github.com/threefoldtech/jumpscale_lib/issues/27
- [x] Improve rivine multisig wallet https://github.com/threefoldtech/jumpscale_lib/issues/125
- [x] Refactor tfchain code to use rivine base https://github.com/threefoldtech/jumpscale_lib/issues/128
- [x] Ability to get a seed from a tfchain wallet https://github.com/threefoldtech/jumpscale_lib/issues/151
- [x] Different generated address handling for the tfchain client https://github.com/threefoldtech/jumpscale_lib/issues/88
- [x] Support uncornfirmed transactions in the balance check https://github.com/threefoldtech/jumpscale_lib/issues/178

**Comment by GlenDC** [comment]
> Add a tft client

`tfchain` client you mean?
